// ---------------------------------------------------------------------------
// pushNotificationService.js — Manage PWA Web Push Subscriptions & Locale Sync
// ---------------------------------------------------------------------------
import { supabase } from '../lib/supabase';
import { useAuthStore } from '../stores/auth';
import { useLocaleStore } from '../stores/locale';
import { DEFAULT_VAPID_PUBLIC_KEY, urlBase64ToUint8Array } from '../utils/pushUtils';

export const pushNotificationService = {
  /**
   * Check if Web Push Notifications are supported in the current browser/OS environment
   */
  isSupported() {
    return (
      typeof window !== 'undefined' &&
      'serviceWorker' in navigator &&
      'PushManager' in window &&
      'Notification' in window
    );
  },

  /**
   * Get current Notification permission state ('granted', 'denied', or 'default')
   */
  getPermissionState() {
    if (!this.isSupported()) return 'denied';
    return Notification.permission;
  },

  /**
   * Get existing PushSubscription object from ServiceWorker registration
   */
  async getSubscription() {
    if (!this.isSupported()) return null;
    try {
      const reg = await navigator.serviceWorker.ready;
      return await reg.pushManager.getSubscription();
    } catch (e) {
      console.warn('[PushService] Error getting subscription:', e);
      return null;
    }
  },

  /**
   * Subscribe user device to Web Push and save subscription details + language preference to Supabase
   */
  async subscribeUser() {
    if (!this.isSupported()) {
      throw new Error('Web Push is not supported in this browser.');
    }

    // 1. Request Notification permission
    const permission = await Notification.requestPermission();
    if (permission !== 'granted') {
      throw new Error('Notification permission denied by user.');
    }

    // 2. Register / wait for Service Worker
    const reg = await navigator.serviceWorker.ready;

    // 3. Subscribe with VAPID Key
    const applicationServerKey = urlBase64ToUint8Array(DEFAULT_VAPID_PUBLIC_KEY);
    let subscription = await reg.pushManager.getSubscription();

    if (!subscription) {
      subscription = await reg.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey,
      });
    }

    const subJson = subscription.toJSON();
    const endpoint = subJson.endpoint;
    const p256dh = subJson.keys?.p256dh;
    const authKey = subJson.keys?.auth;

    if (!endpoint || !p256dh || !authKey) {
      throw new Error('Invalid PushSubscription payload generated by browser.');
    }

    // 4. Save subscription + user language preference to Supabase
    const authStore = useAuthStore();
    const localeStore = useLocaleStore();

    if (!authStore.user || !authStore.familyId) {
      throw new Error('User authentication state missing.');
    }

    const payload = {
      user_id: authStore.user.id,
      family_id: authStore.familyId,
      endpoint,
      p256dh,
      auth: authKey,
      locale: localeStore.currentLocale || 'en',
      user_agent: navigator.userAgent,
      updated_at: new Date().toISOString(),
    };

    const { data, error } = await supabase
      .from('push_subscriptions')
      .upsert([payload], { onConflict: 'endpoint' })
      .select();

    if (error) {
      console.error('[PushService] Failed to save subscription to DB:', error);
      throw error;
    }

    return { subscription, record: data?.[0] };
  },

  /**
   * Unsubscribe user device from Web Push and remove record from Supabase
   */
  async unsubscribeUser() {
    if (!this.isSupported()) return;

    try {
      const reg = await navigator.serviceWorker.ready;
      const subscription = await reg.pushManager.getSubscription();

      if (subscription) {
        const endpoint = subscription.endpoint;

        // Delete from Supabase DB
        await supabase
          .from('push_subscriptions')
          .delete()
          .eq('endpoint', endpoint);

        // Unsubscribe from browser PushManager
        await subscription.unsubscribe();
      }
    } catch (e) {
      console.error('[PushService] Unsubscribe error:', e);
      throw e;
    }
  },

  /**
   * Sync active subscriptions locale whenever user changes language preference in-app
   */
  async syncLocale(newLocale) {
    if (!this.isSupported() || !newLocale) return;

    try {
      const authStore = useAuthStore();
      if (!authStore.user) return;

      const sub = await this.getSubscription();
      if (!sub) return;

      const { error } = await supabase
        .from('push_subscriptions')
        .update({ locale: newLocale, updated_at: new Date().toISOString() })
        .eq('endpoint', sub.endpoint);

      if (error) {
        console.warn('[PushService] Failed to sync subscription locale:', error);
      }
    } catch (e) {
      console.warn('[PushService] syncLocale error:', e);
    }
  },
};
